/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);
ast_node* adjustCond(ast_node * node);

#line 91 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_FLOAT_LITERAL = 4,            /* T_FLOAT_LITERAL  */
  YYSYMBOL_T_ID = 5,                       /* T_ID  */
  YYSYMBOL_T_INT = 6,                      /* T_INT  */
  YYSYMBOL_T_FLOAT = 7,                    /* T_FLOAT  */
  YYSYMBOL_T_VOID = 8,                     /* T_VOID  */
  YYSYMBOL_STRING_LITERAL = 9,             /* STRING_LITERAL  */
  YYSYMBOL_CASE = 10,                      /* CASE  */
  YYSYMBOL_DEFAULT = 11,                   /* DEFAULT  */
  YYSYMBOL_IF = 12,                        /* IF  */
  YYSYMBOL_ELSE = 13,                      /* ELSE  */
  YYSYMBOL_SWITCH = 14,                    /* SWITCH  */
  YYSYMBOL_WHILE = 15,                     /* WHILE  */
  YYSYMBOL_DO = 16,                        /* DO  */
  YYSYMBOL_FOR = 17,                       /* FOR  */
  YYSYMBOL_GOTO = 18,                      /* GOTO  */
  YYSYMBOL_CONTINUE = 19,                  /* CONTINUE  */
  YYSYMBOL_BREAK = 20,                     /* BREAK  */
  YYSYMBOL_RETURN = 21,                    /* RETURN  */
  YYSYMBOL_mn = 22,                        /* mn  */
  YYSYMBOL_23_ = 23,                       /* '{'  */
  YYSYMBOL_24_ = 24,                       /* '}'  */
  YYSYMBOL_25_ = 25,                       /* ','  */
  YYSYMBOL_26_ = 26,                       /* ';'  */
  YYSYMBOL_27_ = 27,                       /* '='  */
  YYSYMBOL_T_ASSDIV = 28,                  /* T_ASSDIV  */
  YYSYMBOL_T_ASSMUL = 29,                  /* T_ASSMUL  */
  YYSYMBOL_T_ASSADD = 30,                  /* T_ASSADD  */
  YYSYMBOL_T_ASSSUB = 31,                  /* T_ASSSUB  */
  YYSYMBOL_T_LOR = 32,                     /* T_LOR  */
  YYSYMBOL_T_LAND = 33,                    /* T_LAND  */
  YYSYMBOL_34_ = 34,                       /* '|'  */
  YYSYMBOL_35_ = 35,                       /* '^'  */
  YYSYMBOL_36_ = 36,                       /* '&'  */
  YYSYMBOL_T_EQ = 37,                      /* T_EQ  */
  YYSYMBOL_T_NE = 38,                      /* T_NE  */
  YYSYMBOL_39_ = 39,                       /* '>'  */
  YYSYMBOL_T_GE = 40,                      /* T_GE  */
  YYSYMBOL_41_ = 41,                       /* '<'  */
  YYSYMBOL_T_LE = 42,                      /* T_LE  */
  YYSYMBOL_T_SL = 43,                      /* T_SL  */
  YYSYMBOL_T_SR = 44,                      /* T_SR  */
  YYSYMBOL_45_ = 45,                       /* '+'  */
  YYSYMBOL_46_ = 46,                       /* '-'  */
  YYSYMBOL_47_ = 47,                       /* '*'  */
  YYSYMBOL_48_ = 48,                       /* '/'  */
  YYSYMBOL_49_ = 49,                       /* '%'  */
  YYSYMBOL_50_ = 50,                       /* '!'  */
  YYSYMBOL_51_ = 51,                       /* '('  */
  YYSYMBOL_52_ = 52,                       /* ')'  */
  YYSYMBOL_53_ = 53,                       /* '['  */
  YYSYMBOL_54_ = 54,                       /* ']'  */
  YYSYMBOL_YYACCEPT = 55,                  /* $accept  */
  YYSYMBOL_CompileUnit = 56,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 57,                   /* FuncDef  */
  YYSYMBOL_FuncParams = 58,                /* FuncParams  */
  YYSYMBOL_FuncParam = 59,                 /* FuncParam  */
  YYSYMBOL_Block = 60,                     /* Block  */
  YYSYMBOL_BlockItemList = 61,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 62,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 63,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 64,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 65,                    /* VarDef  */
  YYSYMBOL_BasicType = 66,                 /* BasicType  */
  YYSYMBOL_Statement = 67,                 /* Statement  */
  YYSYMBOL_Expr = 68,                      /* Expr  */
  YYSYMBOL_AddExp = 69,                    /* AddExp  */
  YYSYMBOL_AddOp = 70,                     /* AddOp  */
  YYSYMBOL_MulExp = 71,                    /* MulExp  */
  YYSYMBOL_MulOp = 72,                     /* MulOp  */
  YYSYMBOL_RelExp = 73,                    /* RelExp  */
  YYSYMBOL_RelOp = 74,                     /* RelOp  */
  YYSYMBOL_EqExp = 75,                     /* EqExp  */
  YYSYMBOL_AndExp = 76,                    /* AndExp  */
  YYSYMBOL_CondExp = 77,                   /* CondExp  */
  YYSYMBOL_UnaryExp = 78,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 79,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 80,             /* RealParamList  */
  YYSYMBOL_LVal = 81,                      /* LVal  */
  YYSYMBOL_IfStmt = 82,                    /* IfStmt  */
  YYSYMBOL_While = 83,                     /* While  */
  YYSYMBOL_For = 84,                       /* For  */
  YYSYMBOL_DoWhile = 85                    /* DoWhile  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  9
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   226

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  55
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  31
/* YYNRULES -- Number of rules.  */
#define YYNRULES  78
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  144

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   289


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    50,     2,     2,     2,    49,    36,     2,
      51,    52,    47,    45,    25,    46,     2,    48,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    26,
      41,    27,    39,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    53,     2,    54,    35,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    23,    34,    24,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    28,    29,
      30,    31,    32,    33,    37,    38,    40,    42,    43,    44
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   102,   102,   110,   116,   121,   128,   145,   150,   153,
     157,   165,   171,   182,   187,   196,   200,   211,   217,   223,
     231,   240,   249,   257,   258,   259,   266,   272,   278,   283,
     288,   291,   294,   297,   300,   303,   306,   316,   326,   331,
     337,   338,   341,   342,   345,   346,   347,   351,   354,   359,
     360,   361,   362,   365,   366,   367,   370,   371,   378,   379,
     388,   394,   410,   425,   426,   436,   443,   447,   452,   455,
     467,   471,   478,   487,   498,   501,   506,   511,   516
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT",
  "T_FLOAT_LITERAL", "T_ID", "T_INT", "T_FLOAT", "T_VOID",
  "STRING_LITERAL", "CASE", "DEFAULT", "IF", "ELSE", "SWITCH", "WHILE",
  "DO", "FOR", "GOTO", "CONTINUE", "BREAK", "RETURN", "mn", "'{'", "'}'",
  "','", "';'", "'='", "T_ASSDIV", "T_ASSMUL", "T_ASSADD", "T_ASSSUB",
  "T_LOR", "T_LAND", "'|'", "'^'", "'&'", "T_EQ", "T_NE", "'>'", "T_GE",
  "'<'", "T_LE", "T_SL", "T_SR", "'+'", "'-'", "'*'", "'/'", "'%'", "'!'",
  "'('", "')'", "'['", "']'", "$accept", "CompileUnit", "FuncDef",
  "FuncParams", "FuncParam", "Block", "BlockItemList", "BlockItem",
  "VarDecl", "VarDeclExpr", "VarDef", "BasicType", "Statement", "Expr",
  "AddExp", "AddOp", "MulExp", "MulOp", "RelExp", "RelOp", "EqExp",
  "AndExp", "CondExp", "UnaryExp", "PrimaryExp", "RealParamList", "LVal",
  "IfStmt", "While", "For", "DoWhile", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-83)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      92,   -83,   -83,   -83,    55,   -83,   -83,     0,    10,   -83,
     -83,   -83,    43,   -83,   -19,   -83,    -7,   -83,   120,    -1,
      16,   -83,   -83,   -20,   120,   120,   120,   120,   -83,    29,
      69,   -83,   -83,   -83,    31,   -22,   -83,    45,    -2,    36,
     120,   -83,   -83,   -83,     5,   -83,   -83,   120,   -83,   -83,
     -83,   120,    89,   -83,    92,    31,   -83,   -83,   -83,   -83,
      -8,    26,   -83,    69,   -83,    33,    51,   175,    52,    38,
      81,   120,   -83,   -83,   -83,   138,   -83,   -83,    43,   -83,
      88,    84,   -83,   -83,   -83,   -83,   -83,   -83,   120,   -83,
     -83,   120,   120,   104,   120,   -83,   -83,    95,   -83,   -83,
     -83,   120,   -83,    29,    27,    40,    93,    -5,     4,    71,
     101,   -83,   102,   -83,   -83,   -83,   -83,   120,   120,   120,
     120,   120,   175,   175,   120,   120,   -83,    29,    27,    27,
      40,    93,   116,   -83,    13,    -3,   175,   105,   120,   -83,
     -83,    78,   175,   -83
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    23,    24,    25,     0,     2,     3,     0,     0,     1,
       4,     5,     0,    17,    20,    18,    20,    19,     0,     0,
       0,    67,    68,    72,     0,     0,     0,     0,    22,    37,
      38,    42,    60,    69,     0,     0,     8,     0,     0,     0,
       0,    63,    64,    65,     0,    40,    41,     0,    44,    45,
      46,     0,     0,     6,     0,     0,    10,    21,    61,    70,
       0,     0,    66,    39,    43,     0,     0,     0,     0,     0,
       0,     0,    11,    36,    28,     0,    13,    16,     0,    15,
       0,    69,    30,    31,    33,    32,     9,     7,     0,    62,
      73,     0,     0,     0,     0,    35,    34,     0,    12,    14,
      29,     0,    71,    47,    53,    56,    58,     0,     0,     0,
       0,    26,     0,    49,    50,    51,    52,     0,     0,     0,
       0,     0,     0,     0,     0,     0,    27,    48,    54,    55,
      57,    59,    75,    76,     0,     0,     0,     0,     0,    74,
      78,     0,     0,    77
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
     -83,   -83,   128,   -83,    79,    -6,   -83,    61,    14,   -83,
     125,   -17,   -63,   -18,    85,   -83,    91,   -83,   -29,   -83,
      28,    30,   -82,   -13,   -83,   -83,   -51,   -83,   -83,   -83,
     -83
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,     4,     5,    35,    36,    74,    75,    76,    77,     7,
      15,     8,    79,    80,    29,    47,    30,    51,   104,   117,
     105,   106,   107,    31,    32,    60,    33,    82,    83,    84,
      85
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      28,    81,    37,    54,    93,     1,     2,     3,    18,    44,
     108,    41,    42,    43,     6,    14,    81,    88,    11,    38,
      18,    59,    61,   138,    81,    12,    13,   121,    53,   121,
      55,    39,    19,    40,    20,    78,   121,    37,    64,    21,
      22,    23,   134,   135,    89,   121,    20,   122,    16,    87,
      56,    34,    57,    97,    52,     9,   123,    62,    78,   132,
     133,     1,     2,     3,    95,   137,   113,   114,   115,   116,
     102,    81,    81,   139,    45,    46,   110,   118,   119,   143,
      90,    24,    25,   112,    91,    81,    26,    27,    58,   128,
     129,    81,    21,    22,    23,     1,     2,     3,     1,     2,
       3,    65,    92,    94,    66,    67,    68,    96,    69,    70,
      71,   101,    52,    72,   100,    73,    48,    49,    50,   109,
     141,   111,   124,    21,    22,    23,   120,   125,   126,   136,
     142,   140,    10,    86,    24,    25,    99,    17,    63,    26,
      27,    21,    22,    23,     1,     2,     3,     0,   130,     0,
      65,   131,     0,    66,    67,    68,     0,    69,    70,    71,
       0,    52,    98,     0,    73,    24,    25,     0,     0,     0,
      26,    27,     0,     0,     0,     0,   103,   103,    21,    22,
      23,     0,     0,    24,    25,     0,     0,    65,    26,    27,
      66,    67,    68,     0,    69,    70,    71,     0,    52,     0,
       0,    73,   127,   103,   103,   103,   103,     0,     0,   103,
     103,     0,     0,     0,     0,     0,     0,     0,     0,     0,
      24,    25,     0,     0,     0,    26,    27
};

static const yytype_int16 yycheck[] =
{
      18,    52,    19,    25,    67,     6,     7,     8,    27,    27,
      92,    24,    25,    26,     0,     5,    67,    25,     4,     3,
      27,    39,    40,    26,    75,    25,    26,    32,    34,    32,
      52,    51,    51,    53,    53,    52,    32,    54,    51,     3,
       4,     5,   124,   125,    52,    32,    53,    52,     5,    55,
       5,    52,    54,    71,    23,     0,    52,    52,    75,   122,
     123,     6,     7,     8,    26,    52,    39,    40,    41,    42,
      88,   122,   123,   136,    45,    46,    94,    37,    38,   142,
      54,    45,    46,   101,    51,   136,    50,    51,    52,   118,
     119,   142,     3,     4,     5,     6,     7,     8,     6,     7,
       8,    12,    51,    51,    15,    16,    17,    26,    19,    20,
      21,    27,    23,    24,    26,    26,    47,    48,    49,    15,
     138,    26,    51,     3,     4,     5,    33,    26,    26,    13,
      52,    26,     4,    54,    45,    46,    75,    12,    47,    50,
      51,     3,     4,     5,     6,     7,     8,    -1,   120,    -1,
      12,   121,    -1,    15,    16,    17,    -1,    19,    20,    21,
      -1,    23,    24,    -1,    26,    45,    46,    -1,    -1,    -1,
      50,    51,    -1,    -1,    -1,    -1,    91,    92,     3,     4,
       5,    -1,    -1,    45,    46,    -1,    -1,    12,    50,    51,
      15,    16,    17,    -1,    19,    20,    21,    -1,    23,    -1,
      -1,    26,   117,   118,   119,   120,   121,    -1,    -1,   124,
     125,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      45,    46,    -1,    -1,    -1,    50,    51
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     6,     7,     8,    56,    57,    63,    64,    66,     0,
      57,    63,    25,    26,     5,    65,     5,    65,    27,    51,
      53,     3,     4,     5,    45,    46,    50,    51,    68,    69,
      71,    78,    79,    81,    52,    58,    59,    66,     3,    51,
      53,    78,    78,    78,    68,    45,    46,    70,    47,    48,
      49,    72,    23,    60,    25,    52,     5,    54,    52,    68,
      80,    68,    52,    71,    78,    12,    15,    16,    17,    19,
      20,    21,    24,    26,    60,    61,    62,    63,    66,    67,
      68,    81,    82,    83,    84,    85,    59,    60,    25,    52,
      54,    51,    51,    67,    51,    26,    26,    68,    24,    62,
      26,    27,    68,    69,    73,    75,    76,    77,    77,    15,
      68,    26,    68,    39,    40,    41,    42,    74,    37,    38,
      33,    32,    52,    52,    51,    26,    26,    69,    73,    73,
      75,    76,    67,    67,    77,    77,    13,    52,    26,    67,
      26,    68,    52,    67
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    55,    56,    56,    56,    56,    57,    57,    58,    58,
      59,    60,    60,    61,    61,    62,    62,    63,    64,    64,
      65,    65,    65,    66,    66,    66,    67,    67,    67,    67,
      67,    67,    67,    67,    67,    67,    67,    68,    69,    69,
      70,    70,    71,    71,    72,    72,    72,    73,    73,    74,
      74,    74,    74,    75,    75,    75,    76,    76,    77,    77,
      78,    78,    78,    78,    78,    78,    79,    79,    79,    79,
      80,    80,    81,    81,    82,    82,    83,    84,    85
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     1,     3,
       2,     2,     3,     1,     2,     1,     1,     2,     2,     3,
       1,     4,     3,     1,     1,     1,     3,     4,     1,     2,
       1,     1,     1,     1,     2,     2,     1,     1,     1,     3,
       1,     1,     1,     3,     1,     1,     1,     1,     3,     1,
       1,     1,     1,     1,     3,     3,     1,     3,     1,     3,
       1,     3,     4,     2,     2,     2,     3,     1,     1,     1,
       1,     3,     1,     4,     7,     5,     5,     9,     7
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 102 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ASTOP(COMPILE_UNIT), (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1283 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 110 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ASTOP(COMPILE_UNIT), (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1294 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 116 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1304 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 121 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1313 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID '(' ')' Block  */
#line 128 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                       {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1335 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID '(' FuncParams ')' Block  */
#line 145 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                   {
        (yyval.node) = create_func_def((yyvsp[-5].type), (yyvsp[-4].var_id), (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1343 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FuncParams: FuncParam  */
#line 150 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = create_contain_node(ASTOP(FUNC_FORMAL_PARAMS), (yyvsp[0].node));
	}
#line 1351 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FuncParams: FuncParams ',' FuncParam  */
#line 153 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                   {
        (yyval.node)->insert_son_node((yyvsp[0].node));
	}
#line 1359 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FuncParam: BasicType T_ID  */
#line 157 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                           {
        (yyval.node) = ast_node::New((yyvsp[0].var_id));
        (yyval.node)->type = typeAttr2Type((yyvsp[-1].type));
	}
#line 1368 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* Block: '{' '}'  */
#line 165 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ASTOP(BLOCK));
	}
#line 1379 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* Block: '{' BlockItemList '}'  */
#line 171 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1390 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* BlockItemList: BlockItem  */
#line 182 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ASTOP(BLOCK), (yyvsp[0].node));
	}
#line 1400 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* BlockItemList: BlockItemList BlockItem  */
#line 187 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1409 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* BlockItem: Statement  */
#line 196 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1418 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* BlockItem: VarDecl  */
#line 200 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1427 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* VarDecl: VarDeclExpr ';'  */
#line 211 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1435 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* VarDeclExpr: BasicType VarDef  */
#line 217 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
        ast_node * tp = create_type_node((yyvsp[-1].type));

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = create_contain_node(ASTOP(VAR_DECL), tp, (yyvsp[0].node));
	}
#line 1446 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* VarDeclExpr: VarDeclExpr ',' VarDef  */
#line 223 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                 {

		// 插入到变量声明语句
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1456 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* VarDef: T_ID  */
#line 231 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 简单变量定义ID

		// 创建变量ID终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[0].var_id).id);
	}
#line 1470 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* VarDef: T_ID '[' T_DIGIT ']'  */
#line 240 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                               {
		// 数组变量定义ID[n]

		// 创建数组变量节点
		(yyval.node) = create_contain_node(ASTOP(ARRAY_DEF), ast_node::New((yyvsp[-3].var_id)), ast_node::New((yyvsp[-1].integer_num)));

		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[-3].var_id).id);
	}
#line 1484 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* VarDef: T_ID '=' Expr  */
#line 249 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        {
        (yyval.node) = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        (yyval.node)->insert_son_node((yyvsp[0].node));
        free((yyvsp[-2].var_id).id);
    }
#line 1494 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* BasicType: T_INT  */
#line 257 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.type) = (yyvsp[0].type); }
#line 1500 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* BasicType: T_FLOAT  */
#line 258 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  { (yyval.type) = (yyvsp[0].type); }
#line 1506 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* BasicType: T_VOID  */
#line 259 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.type) = (yyvsp[0].type); }
#line 1512 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* Statement: RETURN Expr ';'  */
#line 266 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
		// 返回语句

		// 创建返回节点AST_OP_RETURN，其孩子为Expr，即$2
		(yyval.node) = create_contain_node(ASTOP(RETURN), (yyvsp[-1].node));
	}
#line 1523 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* Statement: LVal '=' Expr ';'  */
#line 272 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
		// 赋值语句

		// 创建一个AST_OP_ASSIGN类型的中间节点，孩子为LVal($1)和Expr($3)
		(yyval.node) = create_contain_node(ASTOP(ASSIGN), (yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1534 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* Statement: Block  */
#line 278 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 语句块
		// 内部已创建block节点，直接传递给Statement
		(yyval.node) = (yyvsp[0].node);
	}
#line 1544 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* Statement: Expr ';'  */
#line 283 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                   {
		// 表达式语句
		// 内部已创建表达式，直接传递给Statement
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1554 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* Statement: IfStmt  */
#line 288 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1562 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* Statement: While  */
#line 291 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1570 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* Statement: DoWhile  */
#line 294 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1578 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* Statement: For  */
#line 297 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1586 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* Statement: BREAK ';'  */
#line 300 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                    {
		(yyval.node) = new ast_node(ASTOP(BREAK));
	}
#line 1594 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* Statement: CONTINUE ';'  */
#line 303 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		(yyval.node) = new ast_node(ASTOP(CONTINUE));
	}
#line 1602 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* Statement: ';'  */
#line 306 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 空语句

		// 直接返回空指针，需要再把语句加入到语句块时要注意判断，空语句不要加入
		(yyval.node) = new ast_node(ASTOP(NULL_STMT));
	}
#line 1613 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* Expr: AddExp  */
#line 316 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 直接传递给归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1622 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* AddExp: MulExp  */
#line 326 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 一目表达式
		// 直接传递到归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1632 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* AddExp: AddExp AddOp MulExp  */
#line 331 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          { // TODO 隐式转换
		// 创建加减运算节点，孩子为AddExp($1)和UnaryExp($3)
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1641 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* AddOp: '+'  */
#line 337 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(ADD); }
#line 1647 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* AddOp: '-'  */
#line 338 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(SUB); }
#line 1653 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* MulExp: UnaryExp  */
#line 341 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.node) = (yyvsp[0].node); }
#line 1659 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* MulExp: MulExp MulOp UnaryExp  */
#line 342 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            { (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1665 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* MulOp: '*'  */
#line 345 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(MUL); }
#line 1671 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* MulOp: '/'  */
#line 346 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(DIV); }
#line 1677 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* MulOp: '%'  */
#line 347 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(MOD); }
#line 1683 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* RelExp: AddExp  */
#line 351 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1691 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* RelExp: RelExp RelOp AddExp  */
#line 354 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1699 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* RelOp: '>'  */
#line 359 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(GT); }
#line 1705 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* RelOp: T_GE  */
#line 360 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.op_type) = (int)ASTOP(GE); }
#line 1711 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* RelOp: '<'  */
#line 361 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(LT); }
#line 1717 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* RelOp: T_LE  */
#line 362 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.op_type) = (int)ASTOP(LE); }
#line 1723 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* EqExp: RelExp  */
#line 365 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.node) = (yyvsp[0].node); }
#line 1729 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* EqExp: EqExp T_EQ RelExp  */
#line 366 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        { (yyval.node) = create_contain_node(ASTOP(EQ), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1735 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* EqExp: EqExp T_NE RelExp  */
#line 367 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        { (yyval.node) = create_contain_node(ASTOP(NE), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1741 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* AndExp: EqExp  */
#line 370 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.node) = adjustCond((yyvsp[0].node)); }
#line 1747 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* AndExp: AndExp T_LAND EqExp  */
#line 371 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ASTOP(LAND), (yyvsp[-2].node), adjustCond((yyvsp[0].node)));
    }
#line 1755 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* CondExp: AndExp  */
#line 378 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.node) = (yyvsp[0].node); }
#line 1761 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* CondExp: CondExp T_LOR AndExp  */
#line 379 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                               {
		(yyval.node) = create_contain_node(ASTOP(LOR), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1769 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* UnaryExp: PrimaryExp  */
#line 388 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 1780 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* UnaryExp: T_ID '(' ')'  */
#line 394 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = create_func_call(name_node, paramListNode);

	}
#line 1801 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* UnaryExp: T_ID '(' RealParamList ')'  */
#line 410 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                     {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = create_func_call(name_node, paramListNode);
	}
#line 1821 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* UnaryExp: '+' UnaryExp  */
#line 425 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       { (yyval.node) = (yyvsp[0].node); }
#line 1827 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* UnaryExp: '-' UnaryExp  */
#line 426 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// TODO 浮点数
        if ((yyvsp[0].node)->node_type==ASTOP(LEAF_LITERAL_INT)) {
            (yyvsp[0].node)->integer_val = -(yyvsp[0].node)->integer_val;
            (yyval.node) = (yyvsp[0].node);
        } else {
            auto v = ast_node::New(digit_int_attr{0,(yyvsp[0].node)->line_no});
            (yyval.node) = create_contain_node(ASTOP(SUB), v, (yyvsp[0].node));
        }
	}
#line 1842 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* UnaryExp: '!' UnaryExp  */
#line 436 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		(yyval.node) = create_contain_node(ASTOP(NOT), (yyvsp[0].node));
	}
#line 1850 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* PrimaryExp: '(' Expr ')'  */
#line 443 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                           {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1859 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* PrimaryExp: T_DIGIT  */
#line 447 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量
		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 1869 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* PrimaryExp: T_FLOAT_LITERAL  */
#line 452 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		(yyval.node) = ast_node::New((yyvsp[0].float_num));
	}
#line 1877 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* PrimaryExp: LVal  */
#line 455 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 1888 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* RealParamList: Expr  */
#line 467 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 1897 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* RealParamList: RealParamList ',' Expr  */
#line 471 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                 {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1906 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* LVal: T_ID  */
#line 478 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 1920 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* LVal: T_ID '[' Expr ']'  */
#line 487 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
		// 数组访问 ID[expr]
		
		// 创建数组访问节点
		(yyval.node) = create_contain_node(ASTOP(ARRAY_ACCESS), ast_node::New((yyvsp[-3].var_id)), (yyvsp[-1].node));
		
		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[-3].var_id).id);
	}
#line 1934 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* IfStmt: IF '(' CondExp ')' Statement ELSE Statement  */
#line 498 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                     {
		(yyval.node) = create_contain_node(ASTOP(IF), (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1942 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* IfStmt: IF '(' CondExp ')' Statement  */
#line 501 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                {
		(yyval.node) = create_contain_node(ASTOP(IF), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1950 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* While: WHILE '(' CondExp ')' Statement  */
#line 506 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                        {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1958 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* For: FOR '(' Expr ';' CondExp ';' Expr ')' Statement  */
#line 511 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                      {
		//$$ = create_contain_node(ast_operator_type::AST_OP_FOR, $3, $5, $7, $9);
	}
#line 1966 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* DoWhile: DO Statement WHILE '(' CondExp ')' ';'  */
#line 516 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                 {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_DOWHILE, (yyvsp[-5].node), (yyvsp[-2].node));
	}
#line 1974 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 1978 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 520 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}

// 转换条件 a -> a!=0，保证条件式内无NOT节点
ast_node* adjustCond(ast_node *node) {
    // TODO 浮点数
    auto x = node->node_type;
    if (ASTOP(EQ)<=x && x<=ASTOP(LE)) return node;
    auto v = ast_node::New(digit_int_attr{0,yylineno});
    int tp = (int)ASTOP(NE);
    while (node->node_type==ASTOP(NOT)) {
        tp = (((int)ASTOP(EQ))^((int)ASTOP(NE)))^tp;
        node = node->sons[0];
    }
    return create_contain_node(ast_operator_type(tp), node, v);
}
