/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"

#include "ArrayType.h"

#include <vector>

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);
ast_node* adjustCond(ast_node * node);
void adjustInit(const ArrayType *type, ast_node *node);

#line 96 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_FLOAT_LITERAL = 4,            /* T_FLOAT_LITERAL  */
  YYSYMBOL_T_ID = 5,                       /* T_ID  */
  YYSYMBOL_T_INT = 6,                      /* T_INT  */
  YYSYMBOL_T_FLOAT = 7,                    /* T_FLOAT  */
  YYSYMBOL_T_VOID = 8,                     /* T_VOID  */
  YYSYMBOL_STRING_LITERAL = 9,             /* STRING_LITERAL  */
  YYSYMBOL_CONST = 10,                     /* CONST  */
  YYSYMBOL_CASE = 11,                      /* CASE  */
  YYSYMBOL_DEFAULT = 12,                   /* DEFAULT  */
  YYSYMBOL_IF = 13,                        /* IF  */
  YYSYMBOL_ELSE = 14,                      /* ELSE  */
  YYSYMBOL_SWITCH = 15,                    /* SWITCH  */
  YYSYMBOL_WHILE = 16,                     /* WHILE  */
  YYSYMBOL_DO = 17,                        /* DO  */
  YYSYMBOL_FOR = 18,                       /* FOR  */
  YYSYMBOL_GOTO = 19,                      /* GOTO  */
  YYSYMBOL_CONTINUE = 20,                  /* CONTINUE  */
  YYSYMBOL_BREAK = 21,                     /* BREAK  */
  YYSYMBOL_RETURN = 22,                    /* RETURN  */
  YYSYMBOL_mn = 23,                        /* mn  */
  YYSYMBOL_24_ = 24,                       /* '{'  */
  YYSYMBOL_25_ = 25,                       /* '}'  */
  YYSYMBOL_26_ = 26,                       /* ','  */
  YYSYMBOL_27_ = 27,                       /* ';'  */
  YYSYMBOL_28_ = 28,                       /* '='  */
  YYSYMBOL_T_ASSDIV = 29,                  /* T_ASSDIV  */
  YYSYMBOL_T_ASSMUL = 30,                  /* T_ASSMUL  */
  YYSYMBOL_T_ASSADD = 31,                  /* T_ASSADD  */
  YYSYMBOL_T_ASSSUB = 32,                  /* T_ASSSUB  */
  YYSYMBOL_T_LOR = 33,                     /* T_LOR  */
  YYSYMBOL_T_LAND = 34,                    /* T_LAND  */
  YYSYMBOL_35_ = 35,                       /* '|'  */
  YYSYMBOL_36_ = 36,                       /* '^'  */
  YYSYMBOL_37_ = 37,                       /* '&'  */
  YYSYMBOL_T_EQ = 38,                      /* T_EQ  */
  YYSYMBOL_T_NE = 39,                      /* T_NE  */
  YYSYMBOL_40_ = 40,                       /* '>'  */
  YYSYMBOL_T_GE = 41,                      /* T_GE  */
  YYSYMBOL_42_ = 42,                       /* '<'  */
  YYSYMBOL_T_LE = 43,                      /* T_LE  */
  YYSYMBOL_T_SL = 44,                      /* T_SL  */
  YYSYMBOL_T_SR = 45,                      /* T_SR  */
  YYSYMBOL_46_ = 46,                       /* '+'  */
  YYSYMBOL_47_ = 47,                       /* '-'  */
  YYSYMBOL_48_ = 48,                       /* '*'  */
  YYSYMBOL_49_ = 49,                       /* '/'  */
  YYSYMBOL_50_ = 50,                       /* '%'  */
  YYSYMBOL_51_ = 51,                       /* '!'  */
  YYSYMBOL_52_ = 52,                       /* '('  */
  YYSYMBOL_53_ = 53,                       /* ')'  */
  YYSYMBOL_54_ = 54,                       /* '['  */
  YYSYMBOL_55_ = 55,                       /* ']'  */
  YYSYMBOL_YYACCEPT = 56,                  /* $accept  */
  YYSYMBOL_CompileUnit = 57,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 58,                   /* FuncDef  */
  YYSYMBOL_FuncParams = 59,                /* FuncParams  */
  YYSYMBOL_FuncParam = 60,                 /* FuncParam  */
  YYSYMBOL_Block = 61,                     /* Block  */
  YYSYMBOL_BlockItemList = 62,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 63,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 64,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 65,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 66,                    /* VarDef  */
  YYSYMBOL_ArrayInitList = 67,             /* ArrayInitList  */
  YYSYMBOL_InitValueList = 68,             /* InitValueList  */
  YYSYMBOL_InitValue = 69,                 /* InitValue  */
  YYSYMBOL_BasicType = 70,                 /* BasicType  */
  YYSYMBOL_Statement = 71,                 /* Statement  */
  YYSYMBOL_Expr = 72,                      /* Expr  */
  YYSYMBOL_AddExp = 73,                    /* AddExp  */
  YYSYMBOL_AddOp = 74,                     /* AddOp  */
  YYSYMBOL_MulExp = 75,                    /* MulExp  */
  YYSYMBOL_MulOp = 76,                     /* MulOp  */
  YYSYMBOL_RelExp = 77,                    /* RelExp  */
  YYSYMBOL_RelOp = 78,                     /* RelOp  */
  YYSYMBOL_EqExp = 79,                     /* EqExp  */
  YYSYMBOL_AndExp = 80,                    /* AndExp  */
  YYSYMBOL_CondExp = 81,                   /* CondExp  */
  YYSYMBOL_UnaryExp = 82,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 83,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 84,             /* RealParamList  */
  YYSYMBOL_LVal = 85,                      /* LVal  */
  YYSYMBOL_ArrayIndexList = 86,            /* ArrayIndexList  */
  YYSYMBOL_IfStmt = 87,                    /* IfStmt  */
  YYSYMBOL_While = 88,                     /* While  */
  YYSYMBOL_For = 89,                       /* For  */
  YYSYMBOL_DoWhile = 90                    /* DoWhile  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  11
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   261

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  56
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  35
/* YYNRULES -- Number of rules.  */
#define YYNRULES  91
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  163

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   290


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    51,     2,     2,     2,    50,    37,     2,
      52,    53,    48,    46,    26,    47,     2,    49,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,    27,
      42,    28,    40,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,    54,     2,    55,    36,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    24,    35,    25,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    29,
      30,    31,    32,    33,    34,    38,    39,    41,    43,    44,
      45
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   111,   111,   119,   125,   130,   137,   154,   159,   162,
     166,   170,   182,   188,   199,   204,   213,   217,   228,   234,
     239,   244,   254,   263,   273,   278,   290,   293,   300,   303,
     309,   312,   318,   319,   320,   327,   333,   336,   342,   347,
     352,   355,   358,   361,   364,   367,   370,   380,   390,   395,
     428,   429,   432,   433,   467,   468,   469,   473,   476,   481,
     482,   483,   484,   487,   488,   489,   492,   493,   500,   501,
     510,   516,   532,   547,   548,   561,   568,   572,   577,   580,
     592,   596,   603,   612,   624,   628,   631,   637,   640,   645,
     650,   655
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT",
  "T_FLOAT_LITERAL", "T_ID", "T_INT", "T_FLOAT", "T_VOID",
  "STRING_LITERAL", "CONST", "CASE", "DEFAULT", "IF", "ELSE", "SWITCH",
  "WHILE", "DO", "FOR", "GOTO", "CONTINUE", "BREAK", "RETURN", "mn", "'{'",
  "'}'", "','", "';'", "'='", "T_ASSDIV", "T_ASSMUL", "T_ASSADD",
  "T_ASSSUB", "T_LOR", "T_LAND", "'|'", "'^'", "'&'", "T_EQ", "T_NE",
  "'>'", "T_GE", "'<'", "T_LE", "T_SL", "T_SR", "'+'", "'-'", "'*'", "'/'",
  "'%'", "'!'", "'('", "')'", "'['", "']'", "$accept", "CompileUnit",
  "FuncDef", "FuncParams", "FuncParam", "Block", "BlockItemList",
  "BlockItem", "VarDecl", "VarDeclExpr", "VarDef", "ArrayInitList",
  "InitValueList", "InitValue", "BasicType", "Statement", "Expr", "AddExp",
  "AddOp", "MulExp", "MulOp", "RelExp", "RelOp", "EqExp", "AndExp",
  "CondExp", "UnaryExp", "PrimaryExp", "RealParamList", "LVal",
  "ArrayIndexList", "IfStmt", "While", "For", "DoWhile", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-104)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     131,  -104,  -104,  -104,   136,    87,  -104,  -104,    -4,    59,
      63,  -104,  -104,  -104,    63,  -104,    15,  -104,    -2,  -104,
    -104,   142,    10,    27,    11,  -104,  -104,    65,   142,   142,
     142,   142,  -104,    30,   103,  -104,  -104,  -104,    67,   -15,
    -104,   102,  -104,   -40,    96,   142,    57,    35,  -104,  -104,
    -104,    74,  -104,  -104,   142,  -104,  -104,  -104,   142,   108,
    -104,   136,    67,    77,  -104,   145,  -104,    79,  -104,  -104,
      -5,  -104,   103,  -104,    88,   106,   195,   115,   146,   150,
     198,  -104,  -104,  -104,   158,  -104,  -104,    63,  -104,   154,
     144,  -104,  -104,  -104,  -104,  -104,  -104,    35,  -104,  -104,
      76,  -104,  -104,  -104,   142,  -104,   142,   142,   168,   142,
    -104,  -104,  -104,   159,  -104,  -104,  -104,   142,  -104,     3,
    -104,    30,    -7,    84,   153,     4,    13,   138,   179,  -104,
     180,  -104,  -104,  -104,  -104,  -104,   142,   142,   142,   142,
     142,   195,   195,   142,   142,  -104,    30,    -7,    -7,    84,
     153,   181,  -104,    39,    73,   195,   187,   142,  -104,  -104,
     165,   195,  -104
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    32,    33,    34,     0,     0,     2,     3,     0,     0,
       0,     1,     4,     5,     0,    18,    22,    19,    22,    20,
      21,     0,     0,     0,    23,    77,    78,    82,     0,     0,
       0,     0,    24,    47,    48,    52,    70,    79,     0,     0,
       8,     0,    85,     0,     0,     0,     0,    83,    73,    74,
      75,     0,    50,    51,     0,    54,    55,    56,     0,     0,
       6,     0,     0,    10,    84,     0,    25,     0,    71,    80,
       0,    76,    49,    53,     0,     0,     0,     0,     0,     0,
       0,    12,    46,    38,     0,    14,    17,     0,    16,     0,
      79,    40,    41,    43,    42,     9,     7,    11,    27,    31,
       0,    28,    30,    86,     0,    72,     0,     0,     0,     0,
      45,    44,    36,     0,    13,    15,    39,     0,    26,     0,
      81,    57,    63,    66,    68,     0,     0,     0,     0,    35,
       0,    29,    59,    60,    61,    62,     0,     0,     0,     0,
       0,     0,     0,     0,     0,    37,    58,    64,    65,    67,
      69,    88,    89,     0,     0,     0,     0,     0,    87,    91,
       0,     0,    90
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
    -104,  -104,   215,  -104,   160,    -9,  -104,   143,    75,  -104,
      37,   182,  -104,   109,    -3,   -71,   -21,   117,  -104,   175,
    -104,    19,  -104,    91,    92,  -103,   -16,  -104,  -104,   -56,
     -18,  -104,  -104,  -104,  -104
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_uint8 yydefgoto[] =
{
       0,     5,     6,    39,    40,    83,    84,    85,    86,     8,
      17,    99,   100,   101,     9,    88,    89,    33,    54,    34,
      58,   122,   136,   123,   124,   125,    35,    36,    70,    37,
      24,    91,    92,    93,    94
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      32,    10,    43,    90,   126,   108,    25,    26,    27,    47,
      51,    61,    48,    49,    50,    64,     1,     2,     3,    41,
      90,   104,    14,    15,    67,    69,    21,    65,    90,    60,
      25,    26,    27,   132,   133,   134,   135,   140,    62,    44,
     153,   154,    73,    21,   102,    97,   140,    19,   105,    28,
      29,    20,    23,    96,    30,    31,    87,   141,    41,   113,
      25,    26,    27,    38,    16,    45,   142,    22,    18,    23,
     151,   152,   140,    28,    29,     7,    52,    53,    30,    31,
      13,    87,    42,   120,   158,    90,    90,    11,   128,    45,
     162,    59,   156,     1,     2,     3,   130,     4,   102,    90,
     157,   118,   119,    28,    29,    90,   140,    63,    30,    31,
      68,    25,    26,    27,     1,     2,     3,    46,     4,    23,
      65,    74,   137,   138,    75,    76,    77,    71,    78,    79,
      80,    23,    59,    81,   103,    82,   160,     1,     2,     3,
     106,     4,     1,     2,     3,    25,    26,    27,    25,    26,
      27,    55,    56,    57,    28,    29,   147,   148,   107,    30,
      31,    25,    26,    27,     1,     2,     3,   109,     4,    65,
      98,    74,   117,   110,    75,    76,    77,   111,    78,    79,
      80,   116,    59,   114,   127,    82,   129,   139,    28,    29,
     143,    28,    29,    30,    31,   155,    30,    31,    25,    26,
      27,    25,    26,    27,    28,    29,   144,   145,    74,    30,
      31,    75,    76,    77,   159,    78,    79,    80,   161,    59,
      12,    95,    82,   121,   121,   112,    66,   115,   131,    72,
     149,     0,   150,     0,     0,     0,     0,     0,     0,     0,
       0,    28,    29,     0,    28,    29,    30,    31,     0,    30,
      31,     0,     0,   146,   121,   121,   121,   121,     0,     0,
     121,   121
};

static const yytype_int16 yycheck[] =
{
      21,     4,    23,    59,   107,    76,     3,     4,     5,    27,
      31,    26,    28,    29,    30,    55,     6,     7,     8,    22,
      76,    26,    26,    27,    45,    46,    28,    24,    84,    38,
       3,     4,     5,    40,    41,    42,    43,    33,    53,    28,
     143,   144,    58,    28,    65,    63,    33,    10,    53,    46,
      47,    14,    54,    62,    51,    52,    59,    53,    61,    80,
       3,     4,     5,    53,     5,    54,    53,    52,     5,    54,
     141,   142,    33,    46,    47,     0,    46,    47,    51,    52,
       5,    84,    55,   104,   155,   141,   142,     0,   109,    54,
     161,    24,    53,     6,     7,     8,   117,    10,   119,   155,
      27,    25,    26,    46,    47,   161,    33,     5,    51,    52,
      53,     3,     4,     5,     6,     7,     8,    52,    10,    54,
      24,    13,    38,    39,    16,    17,    18,    53,    20,    21,
      22,    54,    24,    25,    55,    27,   157,     6,     7,     8,
      52,    10,     6,     7,     8,     3,     4,     5,     3,     4,
       5,    48,    49,    50,    46,    47,   137,   138,    52,    51,
      52,     3,     4,     5,     6,     7,     8,    52,    10,    24,
      25,    13,    28,    27,    16,    17,    18,    27,    20,    21,
      22,    27,    24,    25,    16,    27,    27,    34,    46,    47,
      52,    46,    47,    51,    52,    14,    51,    52,     3,     4,
       5,     3,     4,     5,    46,    47,    27,    27,    13,    51,
      52,    16,    17,    18,    27,    20,    21,    22,    53,    24,
       5,    61,    27,   106,   107,    27,    44,    84,   119,    54,
     139,    -1,   140,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
      -1,    46,    47,    -1,    46,    47,    51,    52,    -1,    51,
      52,    -1,    -1,   136,   137,   138,   139,   140,    -1,    -1,
     143,   144
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     6,     7,     8,    10,    57,    58,    64,    65,    70,
      70,     0,    58,    64,    26,    27,     5,    66,     5,    66,
      66,    28,    52,    54,    86,     3,     4,     5,    46,    47,
      51,    52,    72,    73,    75,    82,    83,    85,    53,    59,
      60,    70,    55,    72,    28,    54,    52,    86,    82,    82,
      82,    72,    46,    47,    74,    48,    49,    50,    76,    24,
      61,    26,    53,     5,    55,    24,    67,    72,    53,    72,
      84,    53,    75,    82,    13,    16,    17,    18,    20,    21,
      22,    25,    27,    61,    62,    63,    64,    70,    71,    72,
      85,    87,    88,    89,    90,    60,    61,    86,    25,    67,
      68,    69,    72,    55,    26,    53,    52,    52,    71,    52,
      27,    27,    27,    72,    25,    63,    27,    28,    25,    26,
      72,    73,    77,    79,    80,    81,    81,    16,    72,    27,
      72,    69,    40,    41,    42,    43,    78,    38,    39,    34,
      33,    53,    53,    52,    27,    27,    73,    77,    77,    79,
      80,    71,    71,    81,    81,    14,    53,    27,    71,    27,
      72,    53,    71
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    56,    57,    57,    57,    57,    58,    58,    59,    59,
      60,    60,    61,    61,    62,    62,    63,    63,    64,    65,
      65,    65,    66,    66,    66,    66,    67,    67,    68,    68,
      69,    69,    70,    70,    70,    71,    71,    71,    71,    71,
      71,    71,    71,    71,    71,    71,    71,    72,    73,    73,
      74,    74,    75,    75,    76,    76,    76,    77,    77,    78,
      78,    78,    78,    79,    79,    79,    80,    80,    81,    81,
      82,    82,    82,    82,    82,    82,    83,    83,    83,    83,
      84,    84,    85,    85,    86,    86,    86,    87,    87,    88,
      89,    90
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     1,     3,
       2,     3,     2,     3,     1,     2,     1,     1,     2,     2,
       3,     3,     1,     2,     3,     4,     3,     2,     1,     3,
       1,     1,     1,     1,     1,     3,     2,     4,     1,     2,
       1,     1,     1,     1,     2,     2,     1,     1,     1,     3,
       1,     1,     1,     3,     1,     1,     1,     1,     3,     1,
       1,     1,     1,     1,     3,     3,     1,     3,     1,     3,
       1,     3,     4,     2,     2,     2,     3,     1,     1,     1,
       1,     3,     1,     2,     3,     2,     4,     7,     5,     5,
       9,     7
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 111 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ASTOP(COMPILE_UNIT), (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1315 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 119 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ASTOP(COMPILE_UNIT), (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1326 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 125 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1336 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 130 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1345 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID '(' ')' Block  */
#line 137 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                       {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1367 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID '(' FuncParams ')' Block  */
#line 154 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                   {
        (yyval.node) = create_func_def((yyvsp[-5].type), (yyvsp[-4].var_id), (yyvsp[0].node), (yyvsp[-2].node));
	}
#line 1375 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FuncParams: FuncParam  */
#line 159 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = create_contain_node(ASTOP(FUNC_FORMAL_PARAMS), (yyvsp[0].node));
	}
#line 1383 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FuncParams: FuncParams ',' FuncParam  */
#line 162 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                   {
        (yyval.node)->insert_son_node((yyvsp[0].node));
	}
#line 1391 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FuncParam: BasicType T_ID  */
#line 166 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                           {
        (yyval.node) = ast_node::New((yyvsp[0].var_id));
        (yyval.node)->type = typeAttr2Type((yyvsp[-1].type));
	}
#line 1400 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FuncParam: BasicType T_ID ArrayIndexList  */
#line 170 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                    {
        (yyval.node) = ast_node::New((yyvsp[-1].var_id));
        Type *tp = typeAttr2Type((yyvsp[-2].type));
        
        // 计算数组维度，
        (yyval.node)->type = tp;
        (yyval.node)->insert_son_node((yyvsp[0].node));
    }
#line 1413 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* Block: '{' '}'  */
#line 182 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ASTOP(BLOCK));
	}
#line 1424 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* Block: '{' BlockItemList '}'  */
#line 188 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1435 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* BlockItemList: BlockItem  */
#line 199 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ASTOP(BLOCK), (yyvsp[0].node));
	}
#line 1445 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* BlockItemList: BlockItemList BlockItem  */
#line 204 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1454 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* BlockItem: Statement  */
#line 213 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1463 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* BlockItem: VarDecl  */
#line 217 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1472 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* VarDecl: VarDeclExpr ';'  */
#line 228 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1480 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* VarDeclExpr: BasicType VarDef  */
#line 234 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
        (yyvsp[0].node)->type = typeAttr2Type((yyvsp[-1].type));
		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = create_contain_node(ASTOP(VAR_DECL), (yyvsp[0].node));
	}
#line 1490 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* VarDeclExpr: CONST BasicType VarDef  */
#line 239 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                             {
        (yyvsp[0].node)->type = typeAttr2Type((yyvsp[-1].type));
        (yyvsp[0].node)->isConst = true;
        (yyval.node) = create_contain_node(ASTOP(VAR_DECL), (yyvsp[0].node));
    }
#line 1500 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* VarDeclExpr: VarDeclExpr ',' VarDef  */
#line 244 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                 {
		// 插入到变量声明语句
        ast_node * s0 = (yyvsp[-2].node)->sons[0];
        (yyvsp[0].node)->type = s0->type;
        (yyvsp[0].node)->isConst = s0->isConst;
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1512 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* VarDef: T_ID  */
#line 254 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 简单变量定义ID

		// 创建变量ID终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[0].var_id).id);
	}
#line 1526 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* VarDef: T_ID ArrayIndexList  */
#line 263 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		// 多维数组变量定义ID[expr1][expr2]...，支持常量表达式
        (yyval.node) = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        
        // 将ArrayIndexList作为子节点保存，用于后续计算维度
        (yyval.node)->insert_son_node((yyvsp[0].node));

		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[-1].var_id).id);
	}
#line 1541 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* VarDef: T_ID '=' Expr  */
#line 273 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        {
        (yyval.node) = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        (yyval.node)->insert_son_node((yyvsp[0].node));
        free((yyvsp[-2].var_id).id);
    }
#line 1551 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* VarDef: T_ID ArrayIndexList '=' ArrayInitList  */
#line 278 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                {
		// 多维数组带初始化定义，支持常量表达式
		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno});
        
        // 将ArrayIndexList和初始化列表作为子节点保存
        (yyval.node)->insert_son_node((yyvsp[-2].node));
        (yyval.node)->insert_son_node((yyvsp[0].node));
		free((yyvsp[-3].var_id).id);
	}
#line 1565 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* ArrayInitList: '{' InitValueList '}'  */
#line 290 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                      {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1573 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* ArrayInitList: '{' '}'  */
#line 293 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
		// 空初始化列表
		(yyval.node) = create_contain_node(ASTOP(ARRAY_INIT), nullptr);
	}
#line 1582 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* InitValueList: InitValue  */
#line 300 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		(yyval.node) = create_contain_node(ASTOP(ARRAY_INIT), (yyvsp[0].node));
	}
#line 1590 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* InitValueList: InitValueList ',' InitValue  */
#line 303 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                      {
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1598 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* InitValue: Expr  */
#line 309 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1606 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* InitValue: ArrayInitList  */
#line 312 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1614 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* BasicType: T_INT  */
#line 318 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.type) = (yyvsp[0].type); }
#line 1620 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* BasicType: T_FLOAT  */
#line 319 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  { (yyval.type) = (yyvsp[0].type); }
#line 1626 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* BasicType: T_VOID  */
#line 320 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.type) = (yyvsp[0].type); }
#line 1632 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* Statement: RETURN Expr ';'  */
#line 327 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
		// 返回语句

		// 创建返回节点AST_OP_RETURN，其孩子为Expr，即$2
		(yyval.node) = create_contain_node(ASTOP(RETURN), (yyvsp[-1].node));
	}
#line 1643 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* Statement: RETURN ';'  */
#line 333 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 {
        (yyval.node) = new ast_node(ASTOP(RETURN));
    }
#line 1651 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* Statement: LVal '=' Expr ';'  */
#line 336 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
		// 赋值语句

		// 创建一个AST_OP_ASSIGN类型的中间节点，孩子为LVal($1)和Expr($3)
		(yyval.node) = create_contain_node(ASTOP(ASSIGN), (yyvsp[-3].node), (yyvsp[-1].node));
	}
#line 1662 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* Statement: Block  */
#line 342 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 语句块
		// 内部已创建block节点，直接传递给Statement
		(yyval.node) = (yyvsp[0].node);
	}
#line 1672 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* Statement: Expr ';'  */
#line 347 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                   {
		// 表达式语句
		// 内部已创建表达式，直接传递给Statement
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1682 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* Statement: IfStmt  */
#line 352 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1690 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* Statement: While  */
#line 355 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1698 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* Statement: DoWhile  */
#line 358 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1706 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* Statement: For  */
#line 361 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1714 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* Statement: BREAK ';'  */
#line 364 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                    {
		(yyval.node) = new ast_node(ASTOP(BREAK));
	}
#line 1722 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* Statement: CONTINUE ';'  */
#line 367 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		(yyval.node) = new ast_node(ASTOP(CONTINUE));
	}
#line 1730 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* Statement: ';'  */
#line 370 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 空语句

		// 直接返回空指针，需要再把语句加入到语句块时要注意判断，空语句不要加入
		(yyval.node) = new ast_node(ASTOP(NULL_STMT));
	}
#line 1741 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* Expr: AddExp  */
#line 380 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
		// 直接传递给归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1750 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* AddExp: MulExp  */
#line 390 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 一目表达式
		// 直接传递到归约后的节点
		(yyval.node) = (yyvsp[0].node);
	}
#line 1760 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* AddExp: AddExp AddOp MulExp  */
#line 395 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          { // TODO 隐式转换
		// 创建加减运算节点，孩子为AddExp($1)和UnaryExp($3)
        bool li = (yyvsp[-2].node)->node_type == ASTOP(LEAF_LITERAL_INT);
        bool lf = (yyvsp[-2].node)->node_type == ASTOP(LEAF_LITERAL_FLOAT);
        bool ri = (yyvsp[0].node)->node_type == ASTOP(LEAF_LITERAL_INT);
        bool rf = (yyvsp[0].node)->node_type == ASTOP(LEAF_LITERAL_FLOAT);
        if (li && rf) {
            lf = true; li = false;
            (yyvsp[-2].node)->float_val = (yyvsp[-2].node)->integer_val;
        } else if (lf && ri) {
            rf = true; ri = false;
            (yyvsp[0].node)->float_val = (yyvsp[0].node)->integer_val;
        }
        if (li && ri) {
            if ((yyvsp[-1].op_type) == (int)ASTOP(ADD))
                (yyvsp[-2].node)->integer_val += (yyvsp[0].node)->integer_val;
            else
                (yyvsp[-2].node)->integer_val -= (yyvsp[0].node)->integer_val;
            (yyval.node) = (yyvsp[-2].node);
            delete (yyvsp[0].node);
        } else if (lf && rf) {
            if ((yyvsp[-1].op_type) == (int)ASTOP(ADD))
                (yyvsp[-2].node)->float_val += (yyvsp[0].node)->float_val;
            else
                (yyvsp[-2].node)->float_val -= (yyvsp[0].node)->float_val;
            (yyval.node) = (yyvsp[-2].node);
            delete (yyvsp[0].node);
        } else {
		    (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node));
        }
	}
#line 1796 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* AddOp: '+'  */
#line 428 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(ADD); }
#line 1802 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* AddOp: '-'  */
#line 429 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(SUB); }
#line 1808 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* MulExp: UnaryExp  */
#line 432 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                 { (yyval.node) = (yyvsp[0].node); }
#line 1814 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* MulExp: MulExp MulOp UnaryExp  */
#line 433 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                            {
    bool li = (yyvsp[-2].node)->node_type == ASTOP(LEAF_LITERAL_INT);
        bool lf = (yyvsp[-2].node)->node_type == ASTOP(LEAF_LITERAL_FLOAT);
        bool ri = (yyvsp[0].node)->node_type == ASTOP(LEAF_LITERAL_INT);
        bool rf = (yyvsp[0].node)->node_type == ASTOP(LEAF_LITERAL_FLOAT);
        if (li && rf) {
            lf = true; li = false;
            (yyvsp[-2].node)->float_val = (yyvsp[-2].node)->integer_val;
        } else if (lf && ri) {
            rf = true; ri = false;
            (yyvsp[0].node)->float_val = (yyvsp[0].node)->integer_val;
        }
        if (li && ri) {
            switch (ast_operator_type((yyvsp[-1].op_type))) {
                case ASTOP(MUL): (yyvsp[-2].node)->integer_val *= (yyvsp[0].node)->integer_val; break;
                case ASTOP(DIV): (yyvsp[-2].node)->integer_val /= (yyvsp[0].node)->integer_val; break;
                default: (yyvsp[-2].node)->integer_val %= (yyvsp[0].node)->integer_val; break;
            }
            (yyval.node) = (yyvsp[-2].node);
            delete (yyvsp[0].node);
        } else if (lf && rf) {
            switch (ast_operator_type((yyvsp[-1].op_type))) {
                case ASTOP(MUL): (yyvsp[-2].node)->float_val *= (yyvsp[0].node)->float_val; break;
                case ASTOP(DIV): (yyvsp[-2].node)->float_val /= (yyvsp[0].node)->float_val; break;
                default: break;
            }
            (yyval.node) = (yyvsp[-2].node);
            delete (yyvsp[0].node);
        } else {
            (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node));
        }
    }
#line 1851 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* MulOp: '*'  */
#line 467 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(MUL); }
#line 1857 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* MulOp: '/'  */
#line 468 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(DIV); }
#line 1863 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* MulOp: '%'  */
#line 469 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(MOD); }
#line 1869 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* RelExp: AddExp  */
#line 473 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               {
		(yyval.node) = (yyvsp[0].node);
	}
#line 1877 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* RelExp: RelExp RelOp AddExp  */
#line 476 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		(yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_type)), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1885 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* RelOp: '>'  */
#line 481 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
           { (yyval.op_type) = (int)ASTOP(GT); }
#line 1891 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* RelOp: T_GE  */
#line 482 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.op_type) = (int)ASTOP(GE); }
#line 1897 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* RelOp: '<'  */
#line 483 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.op_type) = (int)ASTOP(LT); }
#line 1903 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* RelOp: T_LE  */
#line 484 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.op_type) = (int)ASTOP(LE); }
#line 1909 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* EqExp: RelExp  */
#line 487 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.node) = (yyvsp[0].node); }
#line 1915 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* EqExp: EqExp T_EQ RelExp  */
#line 488 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        { (yyval.node) = create_contain_node(ASTOP(EQ), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1921 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* EqExp: EqExp T_NE RelExp  */
#line 489 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                        { (yyval.node) = create_contain_node(ASTOP(NE), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1927 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* AndExp: EqExp  */
#line 492 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              { (yyval.node) = adjustCond((yyvsp[0].node)); }
#line 1933 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* AndExp: AndExp T_LAND EqExp  */
#line 493 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ASTOP(LAND), (yyvsp[-2].node), adjustCond((yyvsp[0].node)));
    }
#line 1941 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* CondExp: AndExp  */
#line 500 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
               { (yyval.node) = (yyvsp[0].node); }
#line 1947 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* CondExp: CondExp T_LOR AndExp  */
#line 501 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                               {
		(yyval.node) = create_contain_node(ASTOP(LOR), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 1955 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* UnaryExp: PrimaryExp  */
#line 510 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 1966 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* UnaryExp: T_ID '(' ')'  */
#line 516 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = create_func_call(name_node, paramListNode);

	}
#line 1987 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* UnaryExp: T_ID '(' RealParamList ')'  */
#line 532 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                     {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = create_func_call(name_node, paramListNode);
	}
#line 2007 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* UnaryExp: '+' UnaryExp  */
#line 547 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       { (yyval.node) = (yyvsp[0].node); }
#line 2013 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* UnaryExp: '-' UnaryExp  */
#line 548 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		// TODO 浮点数
        if ((yyvsp[0].node)->node_type==ASTOP(LEAF_LITERAL_INT)) {
            (yyvsp[0].node)->integer_val = -(yyvsp[0].node)->integer_val;
            (yyval.node) = (yyvsp[0].node);
        } else if ((yyvsp[0].node)->node_type==ASTOP(LEAF_LITERAL_FLOAT)) {
            (yyvsp[0].node)->float_val = -(yyvsp[0].node)->float_val;
            (yyval.node) = (yyvsp[0].node);
        } else {
            auto v = ast_node::New(digit_int_attr{0,(yyvsp[0].node)->line_no});
            (yyval.node) = create_contain_node(ASTOP(SUB), v, (yyvsp[0].node));
        }
	}
#line 2031 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* UnaryExp: '!' UnaryExp  */
#line 561 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                       {
		(yyval.node) = create_contain_node(ASTOP(NOT), (yyvsp[0].node));
	}
#line 2039 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* PrimaryExp: '(' Expr ')'  */
#line 568 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                           {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 2048 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* PrimaryExp: T_DIGIT  */
#line 572 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量
		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 2058 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* PrimaryExp: T_FLOAT_LITERAL  */
#line 577 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                          {
		(yyval.node) = ast_node::New((yyvsp[0].float_num));
	}
#line 2066 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 79: /* PrimaryExp: LVal  */
#line 580 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 左转右，部分需要特殊处理
		(yyval.node) = create_contain_node(ASTOP(L2R), (yyvsp[0].node));
	}
#line 2077 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 80: /* RealParamList: Expr  */
#line 592 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 2086 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 81: /* RealParamList: RealParamList ',' Expr  */
#line 596 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                 {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2095 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 82: /* LVal: T_ID  */
#line 603 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 2109 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 83: /* LVal: T_ID ArrayIndexList  */
#line 612 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		// 多维数组访问 ID[expr1][expr2]...
		
		// 创建多维数组访问节点
		(yyval.node) = create_contain_node(ASTOP(ARRAY_ACCESS), ast_node::New((yyvsp[-1].var_id)), (yyvsp[0].node));
		
		// 对于字符型字面量的字符串空间需要释放
		free((yyvsp[-1].var_id).id);
	}
#line 2123 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 84: /* ArrayIndexList: '[' Expr ']'  */
#line 624 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                              {
		// 创建数组索引列表节点，包含第一个索引
		(yyval.node) = create_contain_node(ASTOP(ARRAY_INDICES), (yyvsp[-1].node));
	}
#line 2132 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 85: /* ArrayIndexList: '[' ']'  */
#line 628 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
              {
        (yyval.node) = create_contain_node(ASTOP(ARRAY_INDICES), ast_node::New(digit_int_attr{0, yylineno}));
    }
#line 2140 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 86: /* ArrayIndexList: ArrayIndexList '[' Expr ']'  */
#line 631 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                      {
		// 向数组索引列表添加新索引
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 2149 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 87: /* IfStmt: IF '(' CondExp ')' Statement ELSE Statement  */
#line 637 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                     {
		(yyval.node) = create_contain_node(ASTOP(IF), (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2157 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 88: /* IfStmt: IF '(' CondExp ')' Statement  */
#line 640 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                {
		(yyval.node) = create_contain_node(ASTOP(IF), (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2165 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 89: /* While: WHILE '(' CondExp ')' Statement  */
#line 645 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                        {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_WHILE, (yyvsp[-2].node), (yyvsp[0].node));
	}
#line 2173 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 90: /* For: FOR '(' Expr ';' CondExp ';' Expr ')' Statement  */
#line 650 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                      {
		//$$ = create_contain_node(ast_operator_type::AST_OP_FOR, $3, $5, $7, $9);
	}
#line 2181 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 91: /* DoWhile: DO Statement WHILE '(' CondExp ')' ';'  */
#line 655 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"
                                                 {
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_DOWHILE, (yyvsp[-5].node), (yyvsp[-2].node));
	}
#line 2189 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2193 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 659 "/media/rainbow/14701F54701F3C44/projects/cpll/compiler/frontend/flexbison/MiniC.y"


// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}

// 转换条件 a -> a!=0，保证条件式内无NOT节点
ast_node* adjustCond(ast_node *node) {
    // TODO 浮点数
    auto x = node->node_type;
    if (ASTOP(EQ)<=x && x<=ASTOP(LE)) return node;
    auto v = ast_node::New(digit_int_attr{0,yylineno});
    int tp = (int)ASTOP(NE);
    while (node->node_type==ASTOP(NOT)) {
        tp = (((int)ASTOP(EQ))^((int)ASTOP(NE)))^tp;
        node = node->sons[0];
    }
    return create_contain_node(ast_operator_type(tp), node, v);
}

// init-list标准化调整
void adjustInit(const ArrayType *type, ast_node *node) {
    
}
